name: Build and Package desugar_jdk_libs_nio

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # 移除 bazelbuild/setup-bazelisk@v3 这个步骤
      # 直接使用预装的 bazelisk 进行构建
      - name: Build desugar_jdk_libs_nio
        run: bazel build //:maven_release_jdk11_nio

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: desugar_jdk_libs_nio_package
          path: bazel-bin/desugar_jdk_libs_jdk11_nio.zip
